services:
  source:
    build: ./source
    container_name: source
    depends_on:
      - lb1
    environment:
      - HOST=lb1
      - PORT=4000
    volumes:
      - ./logs/source:/app/source/logs
    networks:
      - app_net

  lb1:
    build: ./load_balancer
    container_name: lb1
    depends_on:
      - service1
      - service2
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=4000
      - SERVERS=service1:5000,service2:5001
      - LB_ID=1
    volumes:
      - ./logs/lb1:/app/load_balancer/logs
    networks:
      - app_net
    ports:
      - "4000:4000"

  lb2:
    build: ./load_balancer
    container_name: lb2
    depends_on:
      - service3
      - service4
    environment:
      - LISTEN_HOST=0.0.0.0
      - LISTEN_PORT=6000
      - SERVERS=service3:7000,service4:7001
      - LB_ID=2
    volumes:
      - ./logs/lb2:/app/load_balancer/logs
    networks:
      - app_net
    ports:
      - "6000:6000"

  service1:
    build: ./service
    container_name: service1
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=5000
      - FORWARD_HOST=lb2
      - FORWARD_PORT=6000
    volumes:
      - ./logs/service1:/app/service/logs
    depends_on:
      - lb2
    networks:
      - app_net

  service2:
    build: ./service
    container_name: service2
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=5001
      - FORWARD_HOST=lb2
      - FORWARD_PORT=6000
    volumes:
      - ./logs/service2:/app/service/logs
    depends_on:
      - lb2
    networks:
      - app_net

  service3:
    build: ./service
    container_name: service3
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=7000
    volumes:
      - ./logs/service3:/app/service/logs
    networks:
      - app_net

  service4:
    build: ./service
    container_name: service4
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=7001
    volumes:
      - ./logs/service4:/app/service/logs
    networks:
      - app_net

networks:
  app_net:
